In [1]:
import numpy as np

# Numpy array

In [2]:
arr = np.array([3,2,5])

In [3]:
arr

array([3, 2, 5])

In [4]:
len(arr)

3

In [5]:
arr[1]

2

In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(arr[1])

numpy.int64

In [9]:
arr32 = np.array([1,5,6], dtype=np.int32)

In [11]:
arr32

array([1, 5, 6], dtype=int32)

In [12]:
arr * arr32

array([ 3, 10, 30])

In [13]:
# multiplication of arrays with 100 random elements
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [14]:
%time arr1 * arr2

CPU times: user 33 µs, sys: 5 µs, total: 38 µs
Wall time: 44.3 µs


array([6.65449424e-01, 3.55423529e-01, 6.63322517e-02, 6.04339050e-03,
       9.00051180e-01, 2.89618594e-01, 6.47116356e-01, 2.14256830e-04,
       4.64861656e-01, 1.21846278e-01, 1.61447618e-01, 2.99639298e-01,
       1.00394051e-01, 1.27609011e-01, 1.57488790e-01, 4.07578058e-01,
       1.98031777e-01, 2.59208655e-01, 8.17946059e-02, 1.85303789e-01,
       5.14217873e-01, 2.87123169e-03, 1.69598705e-01, 5.78600162e-02,
       2.08624752e-01, 2.29925055e-02, 5.38143041e-01, 2.07621349e-01,
       3.74401460e-01, 2.03268646e-02, 7.68724799e-01, 3.41772822e-01,
       2.37500868e-01, 6.81730070e-03, 1.68087576e-01, 2.79071155e-02,
       2.54801566e-01, 2.48785979e-02, 2.20937386e-01, 1.20759218e-01,
       4.81911900e-01, 2.47838283e-02, 6.37053151e-01, 6.89831184e-02,
       3.87748028e-01, 4.11838073e-01, 3.96224326e-01, 1.51454840e-02,
       6.53756182e-01, 2.57518650e-01, 2.75671099e-01, 8.70040323e-02,
       3.63289985e-01, 8.65251567e-02, 5.34862726e-01, 3.75187440e-01,
      

In [15]:
# dot product of arrays
np.dot(arr, arr32)

43

In [16]:
# dot product of arrays
arr @ arr32

43

In [18]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
v = np.arange(12)
v


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
new_mat = np.arange(9).reshape(3,3)
new_mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
new_mat.shape

(3, 3)

In [28]:
mat2 = new_mat
mat2[1,2] = 222

In [29]:
mat2

array([[  0,   1,   2],
       [  3,   4, 222],
       [  6,   7,   8]])

In [30]:
new_mat

array([[  0,   1,   2],
       [  3,   4, 222],
       [  6,   7,   8]])

In [31]:
# Transpose of a matrix
mat2.T

array([[  0,   3,   6],
       [  1,   4,   7],
       [  2, 222,   8]])

In [33]:
nums = [5, 4, 6]
nums[1:2]

[4]

In [34]:
# Get a row in a matrix
mat2[0]

array([0, 1, 2])

In [35]:
# Get a column in a matrix
mat2[:, 0]

array([0, 3, 6])

In [36]:
mat2[:, 0].reshape(3, 1)

array([[0],
       [3],
       [6]])

In [37]:
mat2[:2, :2]

array([[0, 1],
       [3, 4]])

In [38]:
arr = np.arange(5)

In [39]:
arr[np.array([True, False, False, True, True])]

array([0, 3, 4])

In [40]:
arr > 2

array([False, False, False,  True,  True])

In [41]:
arr[arr > 1]

array([2, 3, 4])

In [42]:
new_arr = np.arange(10)
new_arr[(new_arr > 5)&(new_arr < 8)]

array([6, 7])

In [45]:
new_arr[~(new_arr > 7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
mat = np.random.rand(5, 5)
mat

array([[0.5397975 , 0.75204634, 0.11013134, 0.47753654, 0.01950112],
       [0.285435  , 0.94235442, 0.39188482, 0.31567939, 0.75913513],
       [0.49061984, 0.22084994, 0.76365745, 0.20109141, 0.91251397],
       [0.1055664 , 0.89250519, 0.14309099, 0.48254804, 0.24250428],
       [0.89572761, 0.02122756, 0.08152659, 0.40468206, 0.9374471 ]])

In [47]:
# Standard deviation
mat.std()

0.3114942320964533

In [51]:
new_arr[new_arr % 2 != 0]

array([1, 3, 5, 7, 9])

new_arr[new_arr > new_arr.mean()]

## Broadcasting

In [59]:
barr = np.arange(4)
barr + 4

array([4, 5, 6, 7])

In [60]:
barr / 2

array([0. , 0.5, 1. , 1.5])

## Array operations

In [61]:
v = np.arange(12).reshape(4,3)

In [62]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [63]:
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [65]:
v.any()

True

In [66]:
v.all()

False

In [67]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [70]:
v.prod(0)

array([  0, 280, 880])

In [71]:
# Copying from one array to the other without affecting the original array
v1 = v.copy()

## Serialization
* dumps and loads converts the data into bytes and used to send it over network
* dump and load is used for normal serialization

In [72]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [74]:
v2 = np.loads(data)
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## unfunc

In [75]:
@np.vectorize
def nonegative(n):
    if n < 0:
        return 0
    return n

In [76]:
nonegative(v)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [77]:
nonegative(3)

array(3)

In [78]:
nonegative(-3)

array(0)

In [82]:
n = np.array([1, np.nan, 3])

In [83]:
nonegative(n)

array([ 1., nan,  3.])