In [6]:
import numpy as np
print(np.__version__)

1.13.3


In [7]:
# Create an array with numpy
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Create a boolean array
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [12]:
# Create a 2-D array
arr_2D = np.full((3,3), 5)
arr_2D

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
# Assign values to a 2-D array
arr_2D[0][1] = 4  
arr_2D

array([[5, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
# Extract items that satisfy a condition in an array
# Extract all even items from an array 
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [30]:
# Replace all even items with -1
arr[arr % 2 == 0] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [34]:
# Replace items in an array without affecting the original array
arr = np.arange(10)
rep_arr = np.where(arr % 2 == 0, -1, arr)
print(arr)
rep_arr

[0 1 2 3 4 5 6 7 8 9]


array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [35]:
# Convert a 1D array to a 2D array
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
# Stack 2 arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
# Stack 2 arrays horizontally
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
# Generate custom sequences in an array
a = np.array([1,2,3])
np.concatenate([np.repeat(a,3),np.tile(a,3)], axis = 0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
# Extract common items between 2 arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [50]:
# Remove b from a
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [51]:
# Get the positions where elements of two array match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [52]:
# Extract numbers from a given range
a = np.arange(15)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
a[5:10]

array([5, 6, 7, 8, 9])

In [56]:
# Function that handles scalars to work on numpy arrays
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(a, b):
    if (a >= b):
        return a
    else:
        return b
np.vectorize(maxx, otypes=[int])(a,b)  

array([6, 7, 9, 8, 9, 7, 5])

In [58]:
# Swap columns in 2D array
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [59]:
# Swap rows in 2D array
arr = np.arange(9).reshape(3, 3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [63]:
# Reverse the column of a 2D array
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [65]:
# Create a 2D array containing random items
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[ 9.47930315,  9.36934704,  9.04766763],
       [ 6.48791531,  9.82707839,  8.47859348],
       [ 5.24056115,  7.48306675,  8.59879142],
       [ 9.5010819 ,  7.56760596,  7.49569814],
       [ 9.52521007,  7.61708418,  8.67719356]])

In [68]:
# Show only 3 decimal points
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[ 0.817,  0.251,  0.466],
       [ 0.265,  0.19 ,  0.452],
       [ 0.34 ,  0.4  ,  0.661],
       [ 0.183,  0.005,  0.284],
       [ 0.965,  0.893,  0.039]])

In [69]:
# Limit the number of items in output
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [70]:
# Not limiting the number of items in output
np.set_printoptions(threshold=np.nan)